version: "3.5"
services:
    proxy:
        build: "./proxy"
        depends_on: 
            - api
        ports:
            - "8080:80"
        extra_hosts:
            - "static:172.17.0.1"
    api:
        image: henriquericcio/contacts-backend-dotnet
